# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aikit < Formula
  desc "Manage AI dev assets. Sync once, align everyone."
  homepage "https://github.com/silenceper/aikit"
  version "0.0.1-alpha.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/silenceper/aikit/releases/download/v0.0.1-alpha.4/aikit_0.0.1-alpha.4_darwin_amd64.tar.gz"
      sha256 "8fe97069cfd3a940472d244ae0e87e107e86474683cf697220556106e1fe66cf"

      define_method(:install) do
        bin.install "aikit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/silenceper/aikit/releases/download/v0.0.1-alpha.4/aikit_0.0.1-alpha.4_darwin_arm64.tar.gz"
      sha256 "39d2c237abec347737a9acc3355a8e91dc3c9dee3ac893f967bc0abc1ab69c8f"

      define_method(:install) do
        bin.install "aikit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/silenceper/aikit/releases/download/v0.0.1-alpha.4/aikit_0.0.1-alpha.4_linux_amd64.tar.gz"
      sha256 "2bdcd0522308470010eac16f0b4bfcb8947b608b96e84f98e042d2af24724dba"
      define_method(:install) do
        bin.install "aikit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/silenceper/aikit/releases/download/v0.0.1-alpha.4/aikit_0.0.1-alpha.4_linux_arm64.tar.gz"
      sha256 "aee3905bbfac4e39319588023c9a2c3eef75fae3723a16ded493857765690f01"
      define_method(:install) do
        bin.install "aikit"
      end
    end
  end

  test do
    system "#{bin}/aikit", "version"
  end
end
