# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aikit < Formula
  desc "Manage AI dev assets. Sync once, align everyone."
  homepage "https://github.com/silenceper/aikit"
  version "0.1.2-alpha.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/silenceper/aikit/releases/download/v0.1.2-alpha.1/aikit_0.1.2-alpha.1_darwin_amd64.tar.gz"
      sha256 "6b9b542954ac6888c44fe5a95d32bef6df2703ea8a942217d54badcb89172717"

      define_method(:install) do
        bin.install "aikit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/silenceper/aikit/releases/download/v0.1.2-alpha.1/aikit_0.1.2-alpha.1_darwin_arm64.tar.gz"
      sha256 "a0e85de64da900ab653201a76a3da3594edb34bdc52c7f0d8569498734ce165b"

      define_method(:install) do
        bin.install "aikit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/silenceper/aikit/releases/download/v0.1.2-alpha.1/aikit_0.1.2-alpha.1_linux_amd64.tar.gz"
      sha256 "2d993b61a79952859e03691168ee588cc9dc9430cba09906a85fbfd904650d83"
      define_method(:install) do
        bin.install "aikit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/silenceper/aikit/releases/download/v0.1.2-alpha.1/aikit_0.1.2-alpha.1_linux_arm64.tar.gz"
      sha256 "e7c510b6e18d1a339d277316625f0b665ffd10ec20f07bc2558eb0f710ff808d"
      define_method(:install) do
        bin.install "aikit"
      end
    end
  end

  test do
    system "#{bin}/aikit", "version"
  end
end
