# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aikit < Formula
  desc "Manage AI dev assets. Sync once, align everyone."
  homepage "https://github.com/silenceper/aikit"
  version "0.0.1-alpha.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/silenceper/aikit/releases/download/v0.0.1-alpha.5/aikit_0.0.1-alpha.5_darwin_amd64.tar.gz"
      sha256 "c7f88a581b54f08b9c657fa93b76df185e87f8cc8344975b08afb51ab4a34284"

      define_method(:install) do
        bin.install "aikit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/silenceper/aikit/releases/download/v0.0.1-alpha.5/aikit_0.0.1-alpha.5_darwin_arm64.tar.gz"
      sha256 "8eb92ec89912fff910584cacf8ef187b4de22482d405a85208f27b0d0f56cccf"

      define_method(:install) do
        bin.install "aikit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/silenceper/aikit/releases/download/v0.0.1-alpha.5/aikit_0.0.1-alpha.5_linux_amd64.tar.gz"
      sha256 "fa6fc8f91de14c76e1a50d7908a0487c2a2298c16e4e7ba25c42ac59a059579e"
      define_method(:install) do
        bin.install "aikit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/silenceper/aikit/releases/download/v0.0.1-alpha.5/aikit_0.0.1-alpha.5_linux_arm64.tar.gz"
      sha256 "2fc8dd1f79daaf4729e65198616f163e240463ce000e150905eca94c475a998b"
      define_method(:install) do
        bin.install "aikit"
      end
    end
  end

  test do
    system "#{bin}/aikit", "version"
  end
end
