# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gowatch < Formula
  desc "A command line tool that builds and (re)starts your Go program when it detects file changes"
  homepage "https://github.com/silenceper/gowatch"
  version "1.5.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/silenceper/gowatch/releases/download/v1.5.6/gowatch_Darwin_x86_64.tar.gz"
      sha256 "78e6778b4eb3006f74d17f931abe12728f76e6f015e2edc9aedc9d83e38c24d3"

      def install
        bin.install "gowatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/silenceper/gowatch/releases/download/v1.5.6/gowatch_Darwin_arm64.tar.gz"
      sha256 "978869acf25f64107bad02e5b61094afe637117f33bc66fe8ecb2537be543344"

      def install
        bin.install "gowatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/silenceper/gowatch/releases/download/v1.5.6/gowatch_Linux_x86_64.tar.gz"
      sha256 "a7dbfee13a214b619df0954d79d0b1c756bf5d9121e7c563b7cace2951e9b1f2"
      def install
        bin.install "gowatch"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/silenceper/gowatch/releases/download/v1.5.6/gowatch_Linux_arm64.tar.gz"
      sha256 "f460a6a705b24ca7757d024ebab9219775e8e7a2811e70370f1f4f1b6910bd75"
      def install
        bin.install "gowatch"
      end
    end
  end

  test do
    system "#{bin}/gowatch -v"
  end
end
