# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gowatch < Formula
  desc "A command line tool that builds and (re)starts your Go program when it detects file changes"
  homepage "https://github.com/silenceper/gowatch"
  version "1.5.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/silenceper/gowatch/releases/download/v1.5.6/gowatch_Darwin_x86_64.tar.gz"
      sha256 "d959eb7a6df3b2f48fab5eebbc75c099f1767786aa1e81b5ca89cdf4493f8762"

      def install
        bin.install "gowatch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/silenceper/gowatch/releases/download/v1.5.6/gowatch_Darwin_arm64.tar.gz"
      sha256 "1fab2cb585a98f464b7e501a0d8acf6ee7d8addd91dfc52cfad8ddee3aedc7f7"

      def install
        bin.install "gowatch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/silenceper/gowatch/releases/download/v1.5.6/gowatch_Linux_x86_64.tar.gz"
      sha256 "091cf5e644cb7106a8a8678bbb24637d821d6f4cb5d876610af14378e9bc8090"
      def install
        bin.install "gowatch"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/silenceper/gowatch/releases/download/v1.5.6/gowatch_Linux_arm64.tar.gz"
      sha256 "24962356c1efd9f2f7a6aef55e2392a0959ac454a94c179d396f56f210dfc1a6"
      def install
        bin.install "gowatch"
      end
    end
  end

  test do
    system "#{bin}/gowatch -v"
  end
end
